### ISSUE TITLE
EEPROM data lost

### ISSUE THREAD

**Issue by MartinSwanepoel** [omersiar/RFID522-Door-Unlock#11]
After a power down the data stored in the EEPROM is lost. How can this be prevented ?

Thanks

**Comment by omersiar** [comment]
I believe it can be only avoided with good solid supply of voltage to the micro controller.

http://electronics.stackexchange.com/questions/77695/minimum-voltage-to-avoid-eeprom-corruption-for-atmega328p

other problems you may have encountered probably nothing to do with EEPROM data lost.
