### ISSUE TITLE
I keep getting 'redsolid' was not declared in this scope error

### ISSUE THREAD

**Issue by dannit** [omersiar/RFID522-Door-Unlock#13]

**Comment by omersiar** [comment]
which version are you trying to compile?

**Comment by dannit** [comment]
accesscontrol

**Comment by omersiar** [comment]
accesscontrol version is not finished, do you really want to use it? use library's example which is available at examples menu

**Comment by dannit** [comment]
ok

**Comment by dannit** [comment]
is there any way to add a lcd screen?

**Comment by omersiar** [comment]
sure, if you have a compatible lcd.

check it out complete version

https://github.com/rocadura/Arduino-RFID522-Door-Unlock?files=1
