### ISSUE TITLE
So much trouble to get my PC to accept RFID sketches 

### ISSUE THREAD

**Issue by whinge** [omersiar/RFID522-Door-Unlock#5]
I hope I will not be told Arduino can only open its own sketches yet again help me if you know why?
Thanks

**Comment by omersiar** [comment]
No you dont even need to use arduino to program such atmel microcontroller,
there is a learning curve, have installed mfrc522 library, start from there
6 Ağu 2015 00:38 tarihinde "whinge" <notifications@github.com> yazdı:
